# .pre-commit-config.yaml
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        stages: [pre-commit, pre-merge-commit]
      - id: check-ast
        stages: [pre-commit, pre-merge-commit]
      - id: check-builtin-literals
        stages: [pre-commit, pre-merge-commit]
      - id: check-case-conflict
        stages: [pre-commit, pre-merge-commit]
      - id: check-docstring-first
        stages: [pre-commit, pre-merge-commit]
      - id: check-executables-have-shebangs
        stages: [pre-commit, pre-merge-commit]
      - id: check-json
        stages: [pre-commit, pre-merge-commit]
      - id: check-shebang-scripts-are-executable
        stages: [pre-commit, pre-merge-commit]
      - id: check-merge-conflict
        stages: [pre-commit, pre-merge-commit]
      - id: check-symlinks
        stages: [pre-commit, pre-merge-commit]
      - id: check-toml
        stages: [pre-commit, pre-merge-commit]
      - id: check-yaml
        stages: [pre-commit, pre-merge-commit]
      - id: debug-statements
        stages: [pre-commit, pre-merge-commit]
      - id: destroyed-symlinks
        stages: [pre-commit, pre-merge-commit]
      - id: detect-private-key
        stages: [pre-commit, pre-merge-commit]
      - id: double-quote-string-fixer
        stages: [pre-commit, pre-merge-commit]
      - id: end-of-file-fixer
        stages: [pre-commit, pre-merge-commit]
      - id: fix-byte-order-marker
        stages: [pre-commit, pre-merge-commit]
      - id: fix-encoding-pragma
        stages: [pre-commit, pre-merge-commit]
      - id: forbid-new-submodules
        stages: [pre-commit, pre-merge-commit]
      - id: forbid-submodules
        stages: [pre-commit, pre-merge-commit]
      - id: mixed-line-ending
        stages: [pre-commit, pre-merge-commit]
      - id: name-tests-test
        stages: [pre-commit, pre-merge-commit]
      - id: sort-simple-yaml
        stages: [pre-commit, pre-merge-commit]
      - id: trailing-whitespace
        stages: [pre-commit, pre-merge-commit]
  - repo: https://github.com/hhatto/autopep8
    rev: v2.2.0
    hooks:
      - id: autopep8
        stages: [pre-commit, pre-merge-commit]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        stages: [pre-commit, pre-merge-commit]
